# Generated by Django 4.1.3 on 2022-12-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_question_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_a',
            field=models.CharField(default='Новый вариант ответа', max_length=200, verbose_name='Вариант ответа A'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_b',
            field=models.CharField(default='Новый вариант ответа', max_length=200, verbose_name='Вариант ответа B'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_c',
            field=models.CharField(default='Новый вариант ответа', max_length=200, verbose_name='Вариант ответа C'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_d',
            field=models.CharField(default='Новый вариант ответа', max_length=200, verbose_name='Вариант ответа D'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(choices=[('A', 'Answer_a'), ('B', 'Answer_b'), ('C', 'Answer_c'), ('D', 'Answer_d')], default='A', max_length=2, verbose_name='Правильный вариант ответа'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
