# Generated by Django 4.1.3 on 2022-12-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_a',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант ответа A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_b',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант ответа B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_c',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант ответа C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_d',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант ответа D'),
        ),
    ]
