# Generated by Django 4.1.3 on 2022-12-06 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'Вариант A'), ('B', 'Вариант B'), ('C', 'Вариант C'), ('D', 'Вариант D')], max_length=8, verbose_name='Правильные варианты'),
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата создания записи')),
                ('updated', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата ред-ия записи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Подкатегория тестов')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Уникальная строка')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='quiz.quizcategory', verbose_name='Категория тестов')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
