# Generated by Django 4.1.3 on 2022-12-06 10:07

from django.db import migrations
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_question_created_question_is_active_question_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=mptt.fields.TreeManyToManyField(blank=True, related_name='quizs', to='quiz.quizcategory', verbose_name='Категория->Подкатегория'),
        ),
    ]
