# Generated by Django 4.1.3 on 2022-12-08 10:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_quiz_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_a',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_b',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_c',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_d',
            field=models.CharField(default='', max_length=200, verbose_name='Вариант D'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('A', 'answer_a'), ('B', 'answer_b'), ('C', 'answer_c'), ('D', 'answer_d')], max_length=8, verbose_name='Правильные варианты'),
        ),
    ]
